### ISSUE TITLE
Other phones wont display all emoji / Toiset puhelimet ei tunnista kuin muutaman emojin

### ISSUE THREAD

**Issue by jokelap** [JanneEdelman/the-emoji-keyboard#6]
For example Nokia 800 does not display more than few emoji and older Nokia only question marks.

---

Esim: Nokia 800 ei tunnista, kuin muutaman emojin ja vanhempi Nokia pelkkiä kysymysmerkkejä.

**Comment by JanneEdelman** [comment]
Which application you have used to send emoji from Jolla to face this issue? Which application on receiving end?

https://github.com/JanneEdelman/the-emoji-keyboard/wiki/FAQ

---

Millä sovelluksella Jollasta lähetettynä tämä ongelma esiintyy? Mikä sovellus vastaanottavassa päässä?

https://github.com/JanneEdelman/the-emoji-keyboard/wiki/FAQ

**Comment by jokelap** [comment]
Minä lähetin Jollalla normaalilla tekstiviestillä ja vastaan otin Nokia 800 normaalisti.

**Comment by jokelap** [comment]
En ole vielä kokeillut mitakuuluu ohjelmalla.

**Comment by JanneEdelman** [comment]
This ain't keyboard layout issue, but instead
1) SMS sending in Jolla does not encode whole Unicode character set properly and thus Emoji won't be sent from Message app correctly.
2) Receiving application and operating system must support Emoji too. If SMS app or OS receiving the message can't handle Emoji properly it typically shows question mark instead of correct emoji symbol.

Mostly Emoji works correctly in SMS receiving in Jolla.

---

Tämä ei ole näppäimistö layout ongelma, vaan
1) Jollan SMS-lähetys ei koodaa koko Unicode-merkistöä oikein ja siksi Emojit pääsääntöisesti eivät lähde Viesti-sovelluksesta oikein
2) Vastaanottavan pään pitää osata myös koko Emoji-merkistö, muuten merkit eivät näy oikein, vaan tyypillisesti juuri kysymysmerkkinä. Lumia 800:n Windows 7 sisältää vain osittaisen Emoji-merkistön ja vanhemmat Nokiat (S40, Symbian) eivät lainkaan. Näistä osa ei myöskään tue Unicode-merkistöä SMS:ssä

Suurimmaksi osaksi Emoji toimii oikein vastaanotetuissa viesteissä.

**Comment by jokelap** [comment]
Kiitos nopeasta vastauksesta. :)

**Comment by JanneEdelman** [comment]
More accurate information: Messaging application in Jolla can't encode correctly Unicode characters more than two bytes wide and thus such characters won't be transfered correctly in messages sent as SMS. Some other parts of OS and its applications suffer from same issue.

---

Tarkennusta tähän: Jollan viestisovellus ei osaa koodata yli kaksitavuisia Unicode-merkkejä oikein ja siksi ne eivät välity lähetetyissä tekstiviesteissä. Myös jotkin muut tekstiä käsittelevät käyttöjärjestelmän ja varusohjelmiston osat kärsivät samasta ongelmasta.
